version: '3'
services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Password123
      - MSSQL_PID=Developer
      - MSSQL_USER=SA
    ports:
      - "1433:1433"
    networks:
      - frontend
    volumes:
      - ./frontend-2023811-2-5-15.bak:/var/opt/mssql/backup/frontend-Full.bak

networks:
  frontend:
      external: true
